### ISSUE TITLE
Gigabyte B450M DS3H: r8169 module not working for Ethernet

### ISSUE THREAD

**Issue by getchoo** [pop-os/linux#56]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 21.04
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
linux-modules-5.11.0-7620-generic:
  Installed: 5.11.0-7620.21~1624379747~21.04~3abeff8
  Candidate: 5.11.0-7620.21~1624379747~21.04~3abeff8
  Version table:
 *** 5.11.0-7620.21~1624379747~21.04~3abeff8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Whenever I reboot my computer, I am unable to connect to my network via ethernet. After running `journalctl -xe` I found the culprit to be the r8169 driver.

**Steps to reproduce (if you know):**
- Reboot computer
- Try to connect to network

**Expected behavior:**
- A kernel message will appear stating the following:
`r8169 0000:04:00.0 enp4s0: rtl_rxtx_empty_cond == 0 (loop: 42, delay: 100)`

**Other Notes:**
- I uploaded the system log after running `modprobe r8169` [here](https://pastebin.com/kPA1wM82).
- The only way to solve this that I have discovered is to:
    - Reboot my computer into my Windows 10 install and then reboot back into Pop!_OS, or
    - Install `r8169-dkms` and run `rmmod r8169 && modprobe r8168` after installation
- I have a Gigabyte B450M DS3H with a Ryzen 2600
- Here is the output of `lspci`:
```
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
```
- Here is the output of `ip link show`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 18:c0:4d:2f:b0:7d brd ff:ff:ff:ff:ff:ff
```

**Comment by jacobgkau** [comment]
Thank you for the additional detail.

> I also don’t understand how it would be a manufacturer issue though,

This bug tracker is for Pop!_OS. While we ship the open-source r8169 driver in the Pop!_OS kernel, we don't develop that driver from scratch; it's developed upstream by the Linux kernel maintainers. We do guarantee that Pop!_OS will be compatible with System76 hardware, which means if the driver had an issue working with a System76 computer, our engineers would fix it. But for non-System76 hardware, if the driver's having a problem with your Ethernet controller and/or the motherboard that it's part of, either Gigabyte, a company who uses the B450M DS3H motherboard, or a kernel contributor with access to that hardware and an interest in resolving the issue would need to develop a fix.

A more appropriate place to report this bug would be either [Ubuntu's kernel bug tracker](https://bugs.launchpad.net/ubuntu/+source/linux/+bugs) or the [upstream Linux kernel bug tracker](https://bugzilla.kernel.org/) (make sure to check for existing bugs before opening a new one.) The main reason I'm saying this is because it's very unlikely Gigabyte or upstream Linux kernel developers will come across the issue here in the Pop!_OS bug tracker, which means opening a bug report here is unlikely to lead to a fix.

**Comment by getchoo** [comment]
I was going to open an issue on the kernel bugzilla but their submission policy states that unless you are using a custom built kernel, you need to open an issue with your distribution, so I decided to open it here first. I'll put a listing on Ubuntu's kernel bug tracker though.

Thanks for your help!
